### ISSUE TITLE
Model Compression

### ISSUE THREAD

**Issue by kalyangvs** [mit-han-lab/lite-transformer#4]
Hi, Can you please provide the code used to compress the model by 18.2 X using pruning and quantization.
Thanks.

**Comment by kalyangvs** [comment]
@Michaelvll Does the quant plus pruning model include other data such as last_optimizer_state, optimizer_history etc..

**Comment by Michaelvll** [comment]
Thank you for asking! We are still cleaning the code for compression. We quantized the model parameters to 8 bits and sensitive prune the model with [NervanaSystems/distiller](https://github.com/NervanaSystems/distiller). We only calculated the model size since the optimizer states are not used in inference.

**Comment by usamec** [comment]
@Michaelvll can you please provide distiller config, which was used?

Also do you prune individual weights, or whole channels/filters/heads?

**Comment by Michaelvll** [comment]
For simplicity, we use sensitivity pruning for our model, which is fine-grained pruning, i.e. pruning the individual weights. You can try on the [configuration](https://gist.github.com/Michaelvll/4d29b3bcde72bd5dec0bcb56d7d534aa) for the WMT En-Fr model with 527M #Multi-Adds.

**Comment by zilunpeng** [comment]
Could you share some more information on how you quantize the model? Did you use NervanaSystems/distiller for quantization?
